### ISSUE TITLE
Failing for precision error

### ISSUE THREAD

**Issue by sam-ulrich1** [lucataco/cog-playground-v2.5-1024px-aesthetic#1]
I keep getting `Input type (c10::Half) and bias type (float) should be the same`

**Comment by sam-ulrich1** [comment]
You can repro by running the preconfigured default

**Comment by raulmabe-labhouse** [comment]
I am getting the same issue. @sam-ulrich1 why did you close it? Is it solved

**Comment by sam-ulrich1** [comment]
> I am getting the same issue. @sam-ulrich1 why did you close it? Is it solved

It seems to be an infra problem from replicate. Only solution I've seen is to wait for the model to be released, then reload it
