### ISSUE TITLE
NSFW checker is flagging basically any image

### ISSUE THREAD

**Issue by sam-ulrich1** [lucataco/cog-playground-v2.5-1024px-aesthetic#2]
I've had multiple completely SFW prompts fail like:

"A playful Code Monkey wearing a stylish cowboy hat and a GIGO-themed t-shirt, sitting on a stack of high-tech gadgets, with a big smile, surrounded by coding books and a Texas-shaped keyboard, in a vibrant and colorful comic book style"

"A sleek, futuristic cyberpunk car, with neon lights outlining its aerodynamic curves, speeding through a dark, dystopian cityscape on a black background. The car's wheels are retractable, making it hover just above the gritty, rain-slicked asphalt. The city is illuminated by towering holographic billboards and the flicker of neon signs, casting an eerie glow on the deserted streets."

**Comment by lucataco** [comment]
Try using the API, that way you can turn off the safety checker
